package com.atguigu.entity;

public class Coach {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.ch_id
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    private Integer chId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.no
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.name
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.age
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    private Byte age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.sex
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.height
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    private Float height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.weight
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    private Float weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.tel
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    private String tel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.ch_id
     *
     * @return the value of coach.ch_id
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    public Integer getChId() {
        return chId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.ch_id
     *
     * @param chId the value for coach.ch_id
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    public void setChId(Integer chId) {
        this.chId = chId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.no
     *
     * @return the value of coach.no
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.no
     *
     * @param no the value for coach.no
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.name
     *
     * @return the value of coach.name
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.name
     *
     * @param name the value for coach.name
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.age
     *
     * @return the value of coach.age
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    public Byte getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.age
     *
     * @param age the value for coach.age
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    public void setAge(Byte age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.sex
     *
     * @return the value of coach.sex
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.sex
     *
     * @param sex the value for coach.sex
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.height
     *
     * @return the value of coach.height
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    public Float getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.height
     *
     * @param height the value for coach.height
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    public void setHeight(Float height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.weight
     *
     * @return the value of coach.weight
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    public Float getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.weight
     *
     * @param weight the value for coach.weight
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    public void setWeight(Float weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.tel
     *
     * @return the value of coach.tel
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.tel
     *
     * @param tel the value for coach.tel
     *
     * @mbggenerated Wed Mar 27 10:46:41 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel;
    }
}