package com.atguigu.entity;

import java.util.Date;

public class Member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mem_id
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    private Integer memId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.no
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.name
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.nickname
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.age
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    private Byte age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.tel
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.height
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    private Float height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.weight
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    private Float weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.birth
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.icon
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.sex
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    private String sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mem_id
     *
     * @return the value of member.mem_id
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    public Integer getMemId() {
        return memId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mem_id
     *
     * @param memId the value for member.mem_id
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    public void setMemId(Integer memId) {
        this.memId = memId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.no
     *
     * @return the value of member.no
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.no
     *
     * @param no the value for member.no
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.name
     *
     * @return the value of member.name
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.name
     *
     * @param name the value for member.name
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.nickname
     *
     * @return the value of member.nickname
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.nickname
     *
     * @param nickname the value for member.nickname
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.age
     *
     * @return the value of member.age
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    public Byte getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.age
     *
     * @param age the value for member.age
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    public void setAge(Byte age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.tel
     *
     * @return the value of member.tel
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.tel
     *
     * @param tel the value for member.tel
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.height
     *
     * @return the value of member.height
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    public Float getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.height
     *
     * @param height the value for member.height
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    public void setHeight(Float height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.weight
     *
     * @return the value of member.weight
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    public Float getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.weight
     *
     * @param weight the value for member.weight
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    public void setWeight(Float weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.birth
     *
     * @return the value of member.birth
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.birth
     *
     * @param birth the value for member.birth
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.icon
     *
     * @return the value of member.icon
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.icon
     *
     * @param icon the value for member.icon
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.sex
     *
     * @return the value of member.sex
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.sex
     *
     * @param sex the value for member.sex
     *
     * @mbggenerated Wed Mar 27 14:57:53 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex;
    }
}